### PR TITLE
Chitchat is now using gulp

### PR DESCRIPTION
**Pull request by LukyVj**
Oops just noticed I forgot to add the live-reload browser side.. 
I'll add it later then ask for a code review <3

### CODE REVIEW

**Comment by Haroenv** [comment]
I haven't ran gulp yet since @LukyVj, it gives errors on my machine.

**Comment by Haroenv** [comment]
fixed #28

**Comment by victormours** [comment]
:thumbsup: looks good as far as the chaplin config goes

**Comment by LukyVj** [comment]
Okay @Haroenv I still have to fix the livereload thingy and we're good to go ! 
Do not hesitate to review the new gulp file tho

**Pull request merged**
