### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by LukyVj** [comment]
If you could add the font-smoothing to mozilla, then :shipit: :D

**Comment by Haroenv** [comment]
@LukyVj :shipit:

**Comment by LukyVj** [comment]
You can ship it :)

**Comment by Haroenv** [comment]
:ship: :boat: :ocean:

**Comment by LukyVj** [comment]
( delete the branch <3 )

**Comment by Haroenv** [comment]
yes master @LukyVj :heart:

**Pull request merged**
