### PR TITLE
bundle update

### PR DESCRIPTION
**Pull request by Haroenv**
@victormours I redid this pull request, let me know if it's good.

### CODE REVIEW

**Comment by victormours** [comment]
:thumbsup: seems good! :shipit:

**Comment by LukyVj** [comment]
@Haroenv @dervondenbergen Will this allow us to use chitchat on uberspace ?

**Comment by Haroenv** [comment]
Well, it now runs on my computer, IDK what version of ruby is installed on the uberspace, but I think it would.

**Comment by LukyVj** [comment]
Okay ! Then let's install it on uberspace at noon ! 
cc @victormours @dervondenbergen

**Comment by dervondenbergen** [comment]
@victormours probbably knows best, what to do to run chitchat on the uberspace

**Comment by LukyVj** [comment]
Yes, probably, I cc'ed you since you're the uberspace owner :)

**Comment by dervondenbergen** [comment]
:+1: it is good to know, as he maybe has questions uberspace related, which i could answer

**Pull request merged**
